spring:
  application:
    name: users-handler-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    jpa:
      repositories:
        bootstrap-mode: default
    
server:
  port: 8090
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
      
token:
  expiration_time : 864000000
  secret: javaadmirer
  
gateway:
  ip: 192.168.0.110
  
 
login:
    url:
      path : /users/login